version: '3.9'
networks:
  bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.27.0.0/24
         gateway: 172.27.0.1
services:
  web:
    build: .
    ports:
      - 8000:8000
    networks:
      bridge:
        ipv4_address: 172.27.0.100  
    depends_on:
      db:
        condition: service_healthy
        restart: true
    
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yt_statistics_db  
    ports:
      - 5432:5432
    networks:
      bridge:
        ipv4_address: 172.27.0.101
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      

      
  